services:
  db:
    image: postgres:15-alpine
    container_name: cmsai_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER"]
      interval: 5s
      retries: 5

  backend:
    build:
      context: ./backend
    image: cmsai-backend:latest
    container_name: cmsai_backend
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: ${DATABASE_URL}
      SECRET_KEY: ${SECRET_KEY}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      ALLOWED_ORIGINS: ${ALLOWED_ORIGINS}
    expose:
      - "8000"

  frontend:
    build:
      context: ./frontend
    image: cmsai-frontend:latest
    container_name: cmsai_frontend
    depends_on:
      - backend
    ports:
      - "80:80"

volumes:
  db_data:
