import { test, expect } from '@playwright/test'

test('Dashboard shows article created by scheduler (stub)', async ({ page }) => {
  await page.route('**/api/v1/articles/', route => {
    route.fulfill({
      status: 200,
      contentType: 'application/json',
      body: JSON.stringify([
        { id: 1, title: 'Auto article', slug: 'auto-1234', body: 'Generated by scheduler', author_id: 1 }
      ])
    })
  })

  await page.goto('/')
  await expect(page.getByText('Auto article')).toBeVisible()
})
