"""seed initial data

Revision ID: 111111111111
Revises: 763e3f8d7028
Create Date: 2025-07-23 00:00:00
"""
from alembic import op
import sqlalchemy as sa
from passlib.context import CryptContext

# revision identifiers
revision = '111111111111'
down_revision = '763e3f8d7028'
branch_labels = None
depends_on = None

pwd_context = CryptContext(schemes=["bcrypt"], deprecated="auto")

def upgrade():
    # Create a default admin user
    hashed_pw = pwd_context.hash("adminpass")
    op.execute(f"INSERT INTO users (email, hashed_password, role, created_at) VALUES ('admin@example.com', '{hashed_pw}', 'admin', NOW())")
    # Insert a sample draft article
    op.execute("INSERT INTO articles (title, content, meta_description, created_at) VALUES ('Sample Article', 'This is a sample article content generated by AI.', 'Sample meta description', NOW())")

def downgrade():
    op.execute("DELETE FROM articles")
    op.execute("DELETE FROM users WHERE email='admin@example.com'")
