from sqlalchemy import Column, Integer, String, Text, DateTime, ForeignKey
from sqlalchemy.orm import relationship
from datetime import datetime
from database import Base                # OK – po fixie z pkt 1


from sqlalchemy.orm import relationship
from typing import TYPE_CHECKING

# … reszta importów …

if TYPE_CHECKING:
    # tylko dla mypy / IDE – nie uruchamia kodu w runtime
    from .version import Version


class Article(Base):
    """Article model, possibly generated by AI and published to WordPress."""
    __tablename__ = "articles"
    id = Column(Integer, primary_key=True)
    title = Column(String(200), nullable=False)
    content = Column(Text, nullable=False)
    meta_description = Column(String(300))
    image_prompt = Column(Text)       # prompt used to generate hero image (if any)
    image_url = Column(Text)         # URL of hero image (on WordPress) if published
    wordpress_id = Column(Integer)   # Post ID on WordPress
    wordpress_url = Column(String(500))  # Public URL of the post on WordPress
    published_at = Column(DateTime)  # Timestamp when published to WordPress
    twitter_posted_at = Column(DateTime)   # Timestamp when shared on Twitter
    instagram_posted_at = Column(DateTime) # Timestamp when shared on Instagram
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)
    # Relationship to versions of this article
    versions = relationship(
        "Version",
        order_by="Version.created_at.desc()",
        back_populates="article",
    )
