name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16-alpine
        env:
          POSTGRES_USER: cms
          POSTGRES_PASSWORD: cms
          POSTGRES_DB: cmsdb
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U cms" --health-interval=10s
          --health-timeout=5s --health-retries=5
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install backend deps
        run: |
          pip install -r backend/requirements.txt
      - name: Run backend tests
        run: |
          pytest backend/tests -q

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install frontend deps
        run: |
          cd frontend && npm ci
      - name: Build frontend
        run: |
          cd frontend && npm run build --if-present
